config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :teachers
  resources :abouts, only: [:index]
  resources :contacts, only: [:new, :create]

  root 'courses#index'
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :courses
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "tony@kyosei.ai",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :category
    belongs_to :teacher
    validates_associated :category
    validates :category, presence: true

    validates_presence_of :title, :description, :length, :startdate, :register_url
    validates :course_img, attachment_presence: true
    has_attached_file :course_img, styles: { course_index: "250x350>", course_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :course_img, content_type: /\Aimage\/.*\z/
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :courses
    validates_presence_of :name, :experience

    has_attached_file :teacher_img, styles: { teacher_index: "250x350>", teacher_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates :teacher_img, attachment_presence: true
    validates_attachment_content_type :teacher_img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:error] = nil
        else
            flash.now[:error] = 'Cannot send message.'
            render :new
        end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :find_course, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
        if params[:category].blank?
            @courses = Course.all.order("startdate ASC") # may switch to start_date
        else
            @category_id = Category.find_by(name: params[:category]).id
            @courses = Course.where(:category_id => @category_id).order("startdate ASC") # may switch to start_date
        end
    end

    def new
        @course = Course.new
        @categories = Category.all.map{ |c| [c.name, c.id] }
        @teachers = Teacher.all.map{ |c| [c.name, c.id] }
    end

    def create
        @course = Course.new(course_params)
        @course.category_id = params[:category_id]
        @course.teacher_id = params[:teacher_id]

        if @course.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def show
    end

    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
        @teachers = Teacher.all.map{ |c| [c.name, c.id] }
    end

    def update
        @course.category_id = params[:category_id]
        @course.teacher_id = params[:teacher_id]
        if @course.update(course_params)
            redirect_to course_path(@course)
        else
            render 'edit'
        end
    end

    def destroy
        @course.destroy
        redirect_to root_path
    end

    private
    def course_params
        params.require(:course).permit(:title, :description, :length, :register_url, :category_id, :course_img, :teacher_id, :startdate)
    end

    def find_course
        @course = Course.find(params[:id])
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :find_teacher, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @teachers = Teacher.all.order("name")
    end
    
    def new
        @teacher = Teacher.new
    end

    def create
        @teacher = Teacher.new(teacher_params)

        if @teacher.save
            redirect_to teachers_path
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @teacher.update(teacher_params)
            redirect_to teacher_path(@teacher)
        else
            render 'edit'
        end
    end

    def destroy
        @teacher.destroy
        redirect_to teachers_path
    end

    private
    def teacher_params
        params.require(:teacher).permit(:name, :experience, :teacher_img)
    end

    def find_teacher
        @teacher = Teacher.find(params[:id])
    end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def to_markdown(text)
    html_render_options = {
      filter_html:     true, # no input tag or textarea
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow' }
    }

    markdown_options = {
      autolink:           true,
      fenced_code_blocks: true,
      lax_spacing:        true,
      no_intra_emphasis:  true,
      strikethrough:      true,
      superscript:        true
    }

    renderer = Redcarpet::Render::HTML.new(html_render_options)
    markdown = Redcarpet::Markdown.new(renderer, markdown_options)
    raw markdown.render(text)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/abouts/index.html.erb
<h1>About Kyosei Academy</h1>
<p>Kyosei Academy 是 Kyosei.ai 的教育訓練部門，負責規劃企業外訓、在職人士與學生的程式學習課程。</p>
<h2>學員回饋</h2>
<h2>合作企業</h2>
<ul>
    <li>玉山銀行</li>
    <li>中國信託商業銀行</li>
</ul>

app/views/contacts/create.html.erb
<h1>Contact Kyosei.ai</h1>

<h2>Thank you for your message!</h2>
<p>We will get back to you soon.</p>

app/views/contacts/new.html.erb
<h1>與我們聯絡</h1>

<%= simple_form_for @contact do |f| %>
  <%= f.input :name, required: true %>
  <%= f.input :email, required: true %>
  <%= f.input :message, as: :text %>
  <div class="hidden">
    <%= f.input :nickname, hint: "Leave this field blank" %>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/courses/_form.html.erb
<%= simple_form_for @course, :html => { :multipart => true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.file_field :course_img %>
  <%= f.input :title %>
  <%= f.input :description, :input_html => {:rows => 10}%>
  <%= f.input :length %>
  <%= select_tag(:teacher_id, options_for_select(@teachers), :prompt => "Select a teacher") %>
  <%= f.input :startdate %>
  <%= f.input :register_url %>
  <%= f.button :submit %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= simple_form_for @course, :html => { :multipart => true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.select :teacher_id, @teachers %>
  <%= f.file_field :course_img %>
  <%= f.input :title %>
  <%= f.input :description, :input_html => {:rows => 10} %>
  <%= f.input :length %>
  <%= f.input :startdate %>
  <%= f.input :register_url %>
  <%= f.button :submit %>
<% end %>

app/views/courses/index.html.erb
<h1><%= params[:category] %></h1>

<% if @courses.count == 0 %>
    <p>There are no courses in this category.</p>
<% else %>
<div class="row">
    <% @courses.each do |course| %>
        <div class="col-md-4"> 
            <a href="/courses/<%= course.id %>">
                <%= image_tag course.course_img.url(:course_index), class: "course" %>
            </a>  
        </div>
    <% end %>
</div>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<div class="row">
    <div class="col-md-4">
        <%= image_tag @course.course_img.url(:course_show), class: "course-show" %>
    </div>
    <div class="col-md-8">
        <h2>課程：<%= @course.title %></h2>
        <h2>類別：<%= @course.category.name %></h2>
        <h4>講師：<%= @course.teacher.name %></h4>
        <h4>時數：<%= @course.length %> 小時</h4>
        <h4>開課日期：<%= @course.startdate %></h4>
        <h4>簡介：</h4>
        <p><%=  to_markdown @course.description %></p>
        <%= link_to "報名", @course.register_url, target: :_blank %>
        <!-- Load Facebook SDK for JavaScript -->
        <div id="fb-root"></div>
            <script>
            (function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=1376340905709983";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>

        <!-- Your share button code -->
        <div class="fb-share-button"
            data-href="<%= request.original_url %>"
            data-layout="button"
            data-size="large"
            data-mobile-iframe="true">
            <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a>
        </div>
    </div>
</div>
<%= link_to "Back", root_path %>
<% if user_signed_in? %>
    <%= link_to "Edit", edit_course_path(@course) %>
    <%= link_to "Delete", course_path(@course), method: :delete, data: {confirm: "Are you sure you want to delete this course?"} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KyoseiAcademy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Kyosei Academy", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Courses", courses_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <% Category.all.each do |category| %>
                    <li class="<%= 'active' if params[:category] == category.name %>">
                      <%= link_to category.name, courses_path(category: category.name), class: "link" %>
                    </li>
                  <% end %>
                </ul>
            </li>
            <li><%= link_to "Teachers", teachers_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", abouts_path %></li>
            <li><%= link_to "Contact", new_contact_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Add Course", new_course_path %></li>
              <li><%= link_to "Add Teacher", new_teacher_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      
    </div>
    <div class="container">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright &copy; <%= Date.today.year %> Kyosei Academy</p>
      </div>
    </footer>
  </body>
</html>

app/views/teachers/_form.html.erb
<%= simple_form_for @teacher, :html => { :multipart => true } do |f| %>
  <%= f.file_field :teacher_img %>
  <%= f.input :name %>
  <%= f.input :experience, :input_html => {:rows => 10} %>
  <%= f.button :submit %>
<% end %>

app/views/teachers/edit.html.erb
<h1>Edit Teacher</h1>

<%= render 'form' %>

app/views/teachers/index.html.erb
<h1>Teachers</h1>

<div class="row">
    <% @teachers.each do |teacher| %>
        <div class="col-md-4"> 
            <a href="/teachers/<%= teacher.id %>">
                <%= image_tag teacher.teacher_img.url(:teacher_index), class: "teacher" %>
            </a>  
        </div>
    <% end %>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

app/views/teachers/show.html.erb
<div class="row">
    <div class="col-md-4">
        <%= image_tag @teacher.teacher_img.url(:teacher_show), class: "teacher-show" %>
    </div>
    <div class="col-md-8">
        <h2><%= @teacher.name %></h2>
        <p><%= to_markdown @teacher.experience %></p>
        <h2>近期課程</h2>
        <% for course in @teacher.courses %>
            <p><%= link_to course.title, course_path(course) %></p>
        <% end %>
    </div>
</div>

<%= link_to "Back", teachers_path %>
<% if user_signed_in? %>
    <%= link_to "Edit", edit_teacher_path(@teacher) %>
    <%= link_to "Delete", teacher_path(@teacher), method: :delete, data: {confirm: "Are you sure you want to delete this teacher?"} %>
<% end %>